#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run generate:project_heirarchy

if [ $? -eq 0 ]; then
  exit 0
else
  echo "npm run generate:project_heirarchy command failed. Aborting commit."
  exit 1
fi
